[package]
name = "send-transactions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sentry = "0.33.0"
# tracing-subscriber = "0.3.16"
rayon = "1.5.3"
